name: GBR System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: pytest tests/ -v

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t gbr-system:${{ github.sha }} .
    
    - name: Test Docker image
      run: |
        docker run -d -p 7860:7860 --name test-container \
          -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
          -e PINECONE_INDEX_NAME=amazon-products \
          -e PINECONE_ENVIRONMENT=us-east-1 \
          gbr-system:${{ github.sha }}
        sleep 10
        curl -f http://localhost:7860/_stcore/health || exit 1
        docker stop test-container


  deploy-hf:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Deploy to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git clone https://$HF_TOKEN@huggingface.co/spaces/Pratik-1406/gbr-system hf-space
        rsync -av --exclude='.git' --exclude='hf-space' . hf-space/
        cd hf-space
        git add .
        git diff --staged --quiet || git commit -m "Deploy from GitHub: ${{ github.sha }}"
        git push
